Repository ManojSatishkumar/msk-components, pull requests merged in 2020-07, with the labels that each got.

#2 Change webpack configuration
  webpack.config.js
Labels: maintenance

#3 created advanced variant for skillset component
  public/Base64Icons.js
  src/modules/resume/skill-set/variants/advanced/contributors.js
  src/modules/resume/skill-set/variants/advanced/index.js
  src/modules/resume/skill-set/variants/advanced/metadata.js
  src/modules/resume/skill-set/variants/advanced/properties.js
  src/modules/resume/skill-set/variants/advanced/render.js
  src/modules/resume/skill-set/variants/basic/properties.js
  src/modules/resume/skill-set/variants/index.js
Labels: enhancement

#6 Added a dense style resume cover
  src/modules/resume/cover/variants/dense/contributors.js
  src/modules/resume/cover/variants/dense/index.js
  src/modules/resume/cover/variants/dense/metadata.js
  src/modules/resume/cover/variants/dense/properties.js
  src/modules/resume/cover/variants/dense/render.js
  src/modules/resume/cover/variants/index.js
Labels: enhancement

#13 Remove react warnings
  app/components/contributors-list.js
  app/components/layout-area.js
  app/components/layout-toolbar.js
  src/modules/resume/experience/variants/basic/render.js
  src/modules/resume/introduction/variants/basic/render.js
  src/modules/resume/projects/variants/basic/render.js
  src/modules/resume/skill-set/variants/basic/render.js
Labels: bug

#12 Add Education Component
  src/modules/resume/education/index.js
  src/modules/resume/education/metadata.js
  src/modules/resume/education/variants/basic/contributors.js
  src/modules/resume/education/variants/basic/index.js
  src/modules/resume/education/variants/basic/metadata.js
  src/modules/resume/education/variants/basic/properties.js
  src/modules/resume/education/variants/basic/render.js
  src/modules/resume/education/variants/index.js
  src/modules/resume/index.js
Labels: enhancement

#8 Added linter and pre-commit and pre-push hooks using Husky
  .eslintignore
  .eslintrc.js
  .huskyrc.json
  app/components/contributors-list.js
  app/components/layout-area.js
  app/components/layout-toolbar.js
  app/components/modules-list.js
  package-lock.json
  package.json
  src/modules/resume/projects/variants/basic/render.js
  src/modules/resume/skill-set/variants/advanced/properties.js
  src/modules/resume/skill-set/variants/advanced/render.js
Labels: maintenance

#15 Social Links component
  src/modules/resume/index.js
  src/modules/resume/social-links/index.js
  src/modules/resume/social-links/metadata.js
  src/modules/resume/social-links/variants/basic/contributors.js
  src/modules/resume/social-links/variants/basic/index.js
  src/modules/resume/social-links/variants/basic/metadata.js
  src/modules/resume/social-links/variants/basic/properties.js
  src/modules/resume/social-links/variants/basic/render.js
  src/modules/resume/social-links/variants/index.js
Labels: enhancement

#38 Added a 'Flag' style resume cover
  src/modules/resume/cover/variants/flag/contributors.js
  src/modules/resume/cover/variants/flag/index.js
  src/modules/resume/cover/variants/flag/metadata.js
  src/modules/resume/cover/variants/flag/properties.js
  src/modules/resume/cover/variants/flag/render.js
  src/modules/resume/cover/variants/index.js
Labels: enhancement

#18 Added new variant in skills model to show skills with percent
  src/modules/resume/skill-set/variants/column/contributors.js
  src/modules/resume/skill-set/variants/column/index.js
  src/modules/resume/skill-set/variants/column/metadata.js
  src/modules/resume/skill-set/variants/column/properties.js
  src/modules/resume/skill-set/variants/column/render.js
  src/modules/resume/skill-set/variants/index.js
Labels: enhancement

#61 Added a 'Circular' style percentage component for skill-set
  src/modules/resume/skill-set/variants/circular/contributors.js
  src/modules/resume/skill-set/variants/circular/index.js
  src/modules/resume/skill-set/variants/circular/metadata.js
  src/modules/resume/skill-set/variants/circular/properties.js
  src/modules/resume/skill-set/variants/circular/render.js
  src/modules/resume/skill-set/variants/index.js
Labels: new-variant

#51 Added: Contributor name on hovering image
  app/components/contributors-list.js
Labels: enhancement
